### ISSUE TITLE
Check square and disk solution with an analytical solution

### ISSUE THREAD

**Issue by jaghili** [master-csmi/2024-m1-scimba-feelpp#76]
1. Solve on $\Omega=$ unit square : 
$$-\Delta u = f$$
with 
$u =0$ on boundary of $\Omega$ 
and $u=\sin(\pi x)\sin(pi y)$ which is zero on the boundary of the unit square and 
and $f=2\pi^2\sin(\pi x) \sin(\pi y)$ 

2. Find a function $u$ which cancels on the boundary of the unit disk centred in $(0,0)$ 
$$u = \sin(\pi(x^2+y^2))$$ 
And find the associated $f$

3. Compute pointwise errors $|u^*(x) - u_{\text{exact}}(x)|$ for all x 
4. Compute $L^2$ error ($||err||^2=\int_\Omega |u - u^*|^2 dx $) 
5. If possible $H^1$ error :  $||err||^2=\int_\Omega |u - u^*|^2 + ||\nabla u - \nabla u^*||dx$ 
6. IN the conclusion:  what is the delta with respect to the objectives ? what has been done? what's next ? difficulties ? etc

**Comment by rtlili** [comment]
$u=\sin(2\pi x)\sin(2\pi y)$
 $f=8\pi^2\sin(2\pi x) \sin(2\pi y)$ 

$u$ which cancels on the boundary of the unit disk centred in $(0,0)$ 
$$u = \sin(\pi(x^2+y^2))$$ 
the associated $f$:  $$-\Delta u = f$$
$$f= 4\pi \sin(\pi(x^2 + y^2)) - 4\pi^2 (x^2 + y^2) \cos(\pi(x^2 + y^2))$$

**Comment by rtlili** [comment]
Still needs work for error computation
